# Generated by Django 3.2.7 on 2021-09-25 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=-1)),
                ('updated_by', models.IntegerField(default=-1)),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField(default='')),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=-1)),
                ('updated_by', models.IntegerField(default=-1)),
                ('deleted', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=-1)),
                ('updated_by', models.IntegerField(default=-1)),
                ('deleted', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=200)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='news.news')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
