# Generated by Django 3.2.8 on 2021-10-19 14:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'likes'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news'},
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='overview',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
