# Generated by Django 3.2.8 on 2021-10-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211019_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=300)),
                ('content_type', models.CharField(max_length=100)),
                ('new_name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=70, unique=True)),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'uploads',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.uploads'),
        ),
    ]
