# Generated by Django 3.2.8 on 2021-10-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accout', '0003_alter_verifytoken_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifytoken',
            old_name='user',
            new_name='auth_user',
        ),
    ]
